### PR TITLE
Remove `dist` scripts, reorg remaining

### PR DESCRIPTION
**Pull request by nicolaskruchten**
Proposed resolution for #209

### CODE REVIEW

**Comment by nicolaskruchten** [comment]
Not sure why tests are failing... "jest not found?"

**Comment by nicolaskruchten** [comment]
Reran tests without cache and that cleared things up

**Comment by VeraZab** [comment]
I think it's alright we remove the dist files, though I believe that for translation keys of the editor we were discussing hosting dictionaries on a cdn, and plotly.js translation keys separately from editor translation keys

To make CI tests rerun, you can also click on the little red 'x' icon, it will bring you to the CI console, (you may be asked to relog back in with github) and then you can click rebuild.

screen shot 2018-01-08 at 6 20 35 pm

**Comment by nicolaskruchten** [comment]
@VeraZab I'm going to need another review post merge

**Comment by VeraZab** [comment]
thanks Nicolas!!

**Pull request merged**
