### PR TITLE
Fix package.json for consumers

### PR DESCRIPTION
**Pull request by gnestor**
This moves react and react-dom from `dependencies` to `peerDependencies` and `devDependencies`. This prevents multiple copies of react from being loaded by consumer apps. 

The same needs to be done for plotly-icons: https://github.com/plotly/plotly-icons/pull/14

When that's merged, we can change the:

```
"plotly-icons": "github:gnestor/plotly-icons#package.json",
``` 

line to:

```
"plotly-icons": "latest",
```

### CODE REVIEW

**Comment by nicolaskruchten** [comment]
This makes sense to me. I didn't realize you could have modules in both peerDeps and devDeps.

**Comment by nicolaskruchten** [comment]
@VeraZab let's get this and the icons one merged in before the next release

**Comment by VeraZab** [comment]
thanks @gnestor I'll make a release for plotly-icons now and then we can change this in your pr and then merge

**Comment by VeraZab** [comment]
ok, plotly-icons 1.1.5 is out, we can make changes here for it, then merge this :) thanks!

**Comment by gnestor** [comment]
@VeraZab Ok, I updated this branch 👍

**Comment by nicolaskruchten** [comment]
💃 once this passes CI.

**Comment by nicolaskruchten** [comment]
Ah, perhaps CI doesn't run on external repos? I'm OK to merge this @VeraZab

**Comment by VeraZab** [comment]
yes @nicolaskruchten ok to merge. there's no conflicts in package.json right?

**Comment by gnestor** [comment]
Github should warn you if there are merge conflicts. It looks mergeable to me. I rebase this to master yesterday 👍

**Comment by nicolaskruchten** [comment]
This is what the UI looks like in github for us now:

image

**Comment by gnestor** [comment]
Ok, check now 👍

**Comment by nicolaskruchten** [comment]
Hehe thanks, but in the meantime I submitted the same changes in a separate PR so they could hit master faster. There's something about our branch-protection setup which is making things hard for cross-repo PRs I think.

**Comment by gnestor** [comment]
Ok, in the future I'll try to submit PRs from branches on this repo (vs. a fork) 👍

**Comment by nicolaskruchten** [comment]
Thanks, and sorry, I'm not sure why this happens...

**Pull request closed without merging**
