### PR TITLE
Multi format text editor options

### PR DESCRIPTION
**Pull request by VeraZab**
screen shot 2018-01-19 at 10 05 27 am

a bit late, but here's what I've got @bpostlethwaite, @nicolaskruchten, @aulneau

### CODE REVIEW

**Comment by VeraZab** [comment]
correctly rebased with added confirmation panel styles
screen shot 2018-01-19 at 9 59 35 am

**Comment by aulneau** [comment]
The styles shuffling looks good to me 👍

**Comment by nicolaskruchten** [comment]
Looks OK to me 💃

**Comment by VeraZab** [comment]
actually closing #268 here too

**Pull request merged**
