### PR TITLE
Not needed dependency

### PR DESCRIPTION
**Pull request by VeraZab**

### CODE REVIEW

**Comment by bpostlethwaite** [comment]
:dancer:

**Comment by nicolaskruchten** [comment]
I'm pretty sure this dependency is still needed, at least as a dev dep: https://github.com/plotly/react-plotly.js-editor/blob/master/examples/simple/src/App.js#L3

**Comment by VeraZab** [comment]
this is why it's in the package.json of examples/simple: https://github.com/plotly/react-plotly.js-editor/blob/master/examples/simple/package.json#L9

**Comment by nicolaskruchten** [comment]
oooh right, I had forgotten that the examples have their own package.json etc, sorry!

**Pull request merged**
